//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T143143_Homework03_051516
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int Id { get; set; }
        public string word1 { get; set; }
        public string Pronounce { get; set; }
        public string Meaninng { get; set; }
        public string explain_EL { get; set; }
        public string explain_VN { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
